# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0001_squashed_0034_compositionnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compositioncomposer',
            options={'ordering': ('composition__title',)},
        ),
        migrations.AlterModelOptions(
            name='voice',
            options={'ordering': ('item__composition__title',)},
        ),
        migrations.AlterField(
            model_name='bibliographypublication',
            name='type',
            field=models.IntegerField(choices=[(1, 'Volume Number'), (2, 'Title of Parent Entry (i.e., Book title, Journal title)'), (3, 'Publisher'), (4, 'Pages'), (5, 'University and Department (for Dissertations)'), (6, 'Degree (for Dissertations)'), (8, 'Series Title (NB: Use Parent Title for journal names)'), (9, 'URL'), (10, 'URL Accessed Date'), (11, 'Translator Statement'), (12, 'Festschrift Dedicatee'), (13, 'Place of Publication'), (14, 'Number of Volumes in Series'), (15, 'ISBN/ISSN/ISMN'), (16, 'Conference name'), (17, 'Conference location'), (18, 'Conference date'), (99, 'General Note')]),
        ),
    ]
