# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnote',
            name='type',
            field=models.IntegerField(choices=[(1, 'General Note'), (2, 'Copying Style'), (3, 'Concordances'), (4, 'Layout'), (5, 'Position on Page'), (6, 'Non-music contents description')]),
        ),
    ]
