# Generated by Django 2.0.4 on 2018-04-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0002_auto_20180312_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecopyist',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'diamm_data'), ('model', 'person')), models.Q(('app_label', 'diamm_data'), ('model', 'organization')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='sourceprovenance',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'diamm_data'), ('model', 'person')), models.Q(('app_label', 'diamm_data'), ('model', 'organization')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='sourcerelationship',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'diamm_data'), ('model', 'person')), models.Q(('app_label', 'diamm_data'), ('model', 'organization')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
