# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0003_auto_20161216_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcenote',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
