# Generated by Django 3.2.16 on 2022-10-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0004_auto_20200606_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionnote',
            name='type',
            field=models.IntegerField(choices=[(1, 'Alternate Title'), (2, 'Pars'), (3, 'General Note')]),
        ),
    ]
