# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0004_sourcenote_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_title',
            field=models.CharField(blank=True, help_text='A title for this item record, ONLY if it is NOT linked to a composition.', max_length=1024, null=True),
        ),
    ]
