# Generated by Django 3.2.16 on 2022-10-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0005_alter_compositionnote_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcebibliography',
            options={'verbose_name_plural': 'Source bibliographies'},
        ),
        migrations.AlterField(
            model_name='item',
            name='source_order',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='sort_order',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True),
        ),
    ]
