# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 11:45
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_str_to_integer(apps, schema_editor):
    mapping = {
        'mixed': 1,
        'foliation': 2,
        'pagination': 3,
        'none': 4
    }
    Source = apps.get_model('diamm_data', 'Source')
    for source in Source.objects.all():
        source.numbering_system = mapping.get(source.numbering_system, None)
        source.save()


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0006_item_legacy_composition'),
    ]

    operations = [
        migrations.RunPython(migrate_str_to_integer),
        migrations.AlterField(
            model_name='source',
            name='numbering_system',
            field=models.IntegerField(blank=True, choices=[(1, 'Mixed Foliation and Pagination'), (2, 'Foliation'), (3, 'Pagination'), (4, 'None / Unknown')], max_length=32, null=True),
        ),
    ]
