# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0007_auto_20161223_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositioncycle',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='diamm_data.Composition'),
        ),
        migrations.AlterField(
            model_name='source',
            name='end_date',
            field=models.IntegerField(blank=True, help_text='Enter the end year as a four digit integer. If the\n                                   precise year is not known, enter it rounding UP to the\n                                   closest known decade, and then century. Examples: 1456, 1460, 1500.\n                                   ', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='numbering_system',
            field=models.IntegerField(blank=True, choices=[(1, 'Mixed Foliation and Pagination'), (2, 'Foliation'), (3, 'Pagination'), (4, 'None / Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='start_date',
            field=models.IntegerField(blank=True, help_text='Enter the start year as a four digit integer. If\n                                     the precise year is not known, enter it rounding DOWN to the closest\n                                     known decade, and then century. Examples: 1456, 1450, 1400.\n                                     ', null=True),
        ),
    ]
