# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0008_auto_20161223_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compositioncycle',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Page'), (2, 'Modern Endpapers'), (3, 'Contemporary Endpapers'), (4, 'Flyleaf'), (5, 'Opening'), (6, 'Bindings'), (7, 'Fragment(s)'), (8, 'Scroll'), (9, 'Additional'), (10, 'Secondary')], null=True),
        ),
        migrations.AlterField(
            model_name='compositioncycle',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='diamm_data.Cycle'),
        ),
    ]
