# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0010_auto_20170123_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='roles',
        ),
        migrations.AlterField(
            model_name='personrole',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='diamm_data.Person'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='diamm_data.Role'),
        ),
    ]
