# Generated by Django 3.2.18 on 2023-06-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0010_archiveidentifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveidentifier',
            name='identifier',
            field=models.CharField(help_text='Do not provide the full URL here; only the identifier.', max_length=512),
        ),
        migrations.AlterField(
            model_name='archiveidentifier',
            name='identifier_type',
            field=models.IntegerField(choices=[(1, 'RISM Online'), (2, 'VIAF'), (3, 'Wikidata'), (4, 'GND (Gemeinsame Normdatei)'), (5, 'MusicBrainz Artist'), (6, 'ORCID'), (7, 'Bibliothèque national de France'), (8, 'Library of Congress')]),
        ),
        migrations.AlterField(
            model_name='personidentifier',
            name='identifier',
            field=models.CharField(help_text='Do not provide the full URL here; only the identifier.', max_length=512),
        ),
        migrations.AlterField(
            model_name='personidentifier',
            name='identifier_type',
            field=models.IntegerField(choices=[(1, 'RISM Online'), (2, 'VIAF'), (3, 'Wikidata'), (4, 'GND (Gemeinsame Normdatei)'), (5, 'MusicBrainz Artist'), (6, 'ORCID'), (7, 'Bibliothèque national de France'), (8, 'Library of Congress')]),
        ),
        migrations.CreateModel(
            name='SourceAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Do not provide the full URL here; only the identifier.', max_length=512)),
                ('identifier_type', models.IntegerField(choices=[(1, 'RISM Online'), (2, 'VIAF'), (3, 'Wikidata'), (4, 'GND (Gemeinsame Normdatei)'), (5, 'MusicBrainz Artist'), (6, 'ORCID'), (7, 'Bibliothèque national de France'), (8, 'Library of Congress')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorities', to='diamm_data.source')),
            ],
        ),
    ]
