# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0011_auto_20170218_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='label',
            field=models.CharField(blank=True, help_text='Former Text voicepart field', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='position',
            field=models.CharField(blank=True, help_text='Former Text positiononpage field', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='sort_order',
            field=models.IntegerField(blank=True, help_text='Used to sort voices e.g., Soprano, Alto, Tenor, Bass', null=True),
        ),
    ]
