# Generated by Django 4.2.2 on 2023-06-27 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0011_auto_20230626_1205"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sourceauthority",
            options={"verbose_name_plural": "Source authorities"},
        ),
    ]
