# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0012_auto_20170318_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcebibliography',
            options={'verbose_name_plural': 'Source Bibliographies'},
        ),
    ]
