# Generated by Django 4.2.3 on 2023-09-29 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0013_person_floruit"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="external",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="external",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="iiif_canvas_uri",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name="SourceManifest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manifest_url", models.CharField(max_length=1024)),
                ("iiif_version", models.IntegerField(choices=[(2, "v2"), (3, "v3")])),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manifests",
                        to="diamm_data.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationIdentifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Do not provide the full URL here; only the identifier.",
                        max_length=512,
                    ),
                ),
                (
                    "identifier_type",
                    models.IntegerField(
                        choices=[
                            (1, "RISM Online"),
                            (2, "VIAF"),
                            (3, "Wikidata"),
                            (4, "GND (Gemeinsame Normdatei)"),
                            (5, "MusicBrainz Artist"),
                            (6, "ORCID"),
                            (7, "Bibliothèque national de France"),
                            (8, "Library of Congress"),
                        ]
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="diamm_data.organization",
                    ),
                ),
            ],
        ),
    ]
