# Generated by Django 5.1.5 on 2025-01-27 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "diamm_data",
            "0014_image_external_page_external_page_iiif_canvas_uri_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagetype",
            options={"ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="image",
            name="height",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="image",
            name="width",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="geographicarea",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="If the area is subordinate to another (e.g., city to country),\n                               you can specify this here. For regions where their historical provenance has changed\n                               (e.g., Alsace and France or Germany; Vienna and Austria or Prussia), you should choose the\n                               present affiliation.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="diamm_data.geographicarea",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="type",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="diamm_data.imagetype",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_title",
            field=models.CharField(
                blank=True,
                help_text='A title for this item record, ONLY if it is NOT linked to a composition. This is for\n                         supplying a name to otherwise untitled things (e.g., "blank page") or\n                         for non-musical titles ("A Poem").\n\n                         Use the Source Attribution field to record variant titles for compositions.\n                 ',
                max_length=1024,
                null=True,
            ),
        ),
    ]
