# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0014_auto_20170325_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcenote',
            name='type',
            field=models.IntegerField(choices=[(1, 'General Description'), (97, 'RISM Description'), (98, 'Census Catalogue of Music Description'), (4, 'Extent Note'), (5, 'Physical Description Note'), (6, 'Binding Note'), (7, 'Ownership Note'), (8, 'Watermark Note'), (9, 'Liminary Note'), (10, 'Notation Note'), (11, 'Date Note'), (12, 'Dedication Note'), (13, 'Ruling Note'), (14, 'Foliation Note'), (15, 'Decoration Note'), (16, 'Contents Note'), (17, 'Surface Note'), (18, 'DIAMM Note'), (99, 'Private Note')]),
        ),
    ]
