# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0015_auto_20170325_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='diamm_data.GeographicArea'),
        ),
    ]
