# Generated by Django 5.1.5 on 2025-02-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0016_natsort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="height",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="width",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
