# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0016_auto_20170326_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivenote',
            options={'ordering': ('archive__name',)},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['source__shelfmark', 'sort_order']},
        ),
        migrations.AddField(
            model_name='geographicarea',
            name='variant_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geographicarea',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If the area is subordinate to another (e.g., city to country),\n                               you can specify this here. For regions where their historical provenance has changed \n                               (e.g., Alsace and France or Germany; Vienna and Austria or Prussia), you should choose the\n                               current affiliation.', null=True, on_delete=django.db.models.deletion.CASCADE, to='diamm_data.GeographicArea'),
        ),
        migrations.AlterField(
            model_name='sourcenote',
            name='type',
            field=models.IntegerField(choices=[(1, 'General Description'), (97, 'RISM Description'), (98, 'Census Catalogue of Music Description'), (4, 'Extent'), (5, 'Physical Description'), (6, 'Binding'), (7, 'Ownership'), (8, 'Watermark'), (9, 'Liminary Note'), (10, 'Notation'), (11, 'Date'), (12, 'Dedication'), (13, 'Ruling'), (14, 'Foliation'), (15, 'Decoration'), (16, 'Contents'), (17, 'Surface'), (18, 'DIAMM Note'), (99, 'Private Note')]),
        ),
    ]
