# Generated by Django 5.1.5 on 2025-02-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0017_alter_image_height_alter_image_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="location",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
