# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0018_auto_20170527_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ('cluster_shelfmark',)},
        ),
    ]
