# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0019_auto_20170623_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
