# Generated by Django 5.1.5 on 2025-02-18 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0019_remove_image_iiif_response_cache"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={"ordering": ["archive__siglum", "sort_order"]},
        ),
    ]
