# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0019_auto_20170527_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='page_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
