# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0020_auto_20170609_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliography',
            options={'ordering': ('created',), 'verbose_name': 'Bibliography entry', 'verbose_name_plural': 'Bibliography entries'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('source_order', 'folio_start')},
        ),
        migrations.AlterModelOptions(
            name='sourcecatalogueentry',
            options={'ordering': ('entry',), 'verbose_name_plural': 'Source catalogue entries'},
        ),
        migrations.AlterField(
            model_name='geographicarea',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If the area is subordinate to another (e.g., city to country),\n                               you can specify this here. For regions where their historical provenance has changed \n                               (e.g., Alsace and France or Germany; Vienna and Austria or Prussia), you should choose the\n                               present affiliation.', null=True, on_delete=django.db.models.deletion.CASCADE, to='diamm_data.GeographicArea'),
        ),
        migrations.AlterField(
            model_name='person',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
