# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0020_auto_20170708_2214'),
        ('diamm_data', '0020_auto_20170609_1636'),
    ]

    operations = [
    ]
