# Generated by Django 5.1.6 on 2025-02-21 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0021_alter_compositionnote_type_alter_voice_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="external_manifest",
            field=models.URLField(
                blank=True,
                help_text="URL to external IIIF manifest. This overrides any DIAMM manifest so it should be left blank \n                     for sources that have DIAMM images attached.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ExternalPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label from the IIIF Canvas", max_length=64
                    ),
                ),
                (
                    "sort_order",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=0,
                        max_digits=100,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_pages",
                        to="diamm_data.source",
                    ),
                ),
            ],
            options={
                "ordering": ["source__shelfmark", "sort_order"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="external_pages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Only use with an external IIIF manifest. Use the 'pages' field for all other sources.",
                related_name="items_external",
                to="diamm_data.externalpage",
            ),
        ),
    ]
