# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 12:22
from __future__ import unicode_literals

import diamm.helpers.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0021_merge_20170708_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='logo',
            field=models.FileField(blank=True, null=True, storage=diamm.helpers.storage.OverwriteStorage(), upload_to='/Users/ahankins/Documents/code/git/diamm/diamm/media/archives'),
        ),
        migrations.AlterField(
            model_name='item',
            name='incipit',
            field=models.FileField(blank=True, null=True, storage=diamm.helpers.storage.OverwriteStorage(), upload_to='/Users/ahankins/Documents/code/git/diamm/diamm/media/rism/incipits'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_title',
            field=models.CharField(blank=True, help_text='A title for this item record, ONLY if it is NOT linked to a composition. This is for\n                         supplying a name to otherwise untitled things (e.g., "blank page") or \n                         for non-musical titles ("A Poem").\n                         \n                         Use the Source Attribution field to record variant titles for compositions.\n                 ', max_length=1024, null=True),
        ),
    ]
