# Generated by Django 5.1.6 on 2025-02-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("diamm_data", "0022_source_external_manifest_externalpage_and_more"),
        ("diamm_data", "0023_remove_source_external_manifest_and_more"),
        ("diamm_data", "0024_alter_sourceurl_type"),
    ]

    dependencies = [
        ("diamm_data", "0021_alter_compositionnote_type_alter_voice_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label from the IIIF Canvas", max_length=64
                    ),
                ),
                (
                    "sort_order",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=0,
                        max_digits=100,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_pages",
                        to="diamm_data.source",
                    ),
                ),
            ],
            options={
                "ordering": ["source__shelfmark", "sort_order"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="external_pages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Only use with an external IIIF manifest. Use the 'pages' field for all other sources.",
                related_name="external_items",
                to="diamm_data.externalpage",
            ),
        ),
        migrations.AlterField(
            model_name="sourceurl",
            name="link",
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="sourceurl",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "IIIF Manifest"),
                    (2, "Host Institution"),
                    (3, "Ancillary"),
                    (4, "External Images"),
                ]
            ),
        ),
    ]
