# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0022_auto_20170716_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcomposer',
            name='composer',
            field=models.ForeignKey(help_text='DO NOT attach a duplicate composer here if this item is attached to a composition.\n                            This field is ONLY to be used to record that a MSS features works by a particular composer,\n                            and should not be used otherwise.', on_delete=django.db.models.deletion.CASCADE, related_name='unattributed_works', to='diamm_data.Person'),
        ),
        migrations.AlterField(
            model_name='itemnote',
            name='type',
            field=models.IntegerField(choices=[(1, 'General Note'), (2, 'Copying Style'), (3, 'Concordances'), (4, 'Layout'), (5, 'Position on Page'), (6, 'Non-music contents description'), (7, 'Indexing or Ordering')]),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Page'), (2, 'Modern Endpapers'), (3, 'Contemporary Endpapers'), (4, 'Flyleaf'), (5, 'Opening'), (6, 'Bindings'), (7, 'Fragment(s)'), (8, 'Scroll'), (9, 'Additional'), (10, 'Secondary')], default=1, null=True),
        ),
    ]
