# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0023_auto_20170716_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
