# Generated by Django 5.1.6 on 2025-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0023_remove_source_external_manifest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceurl",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "IIIF Manifest"),
                    (2, "Host Institution"),
                    (3, "Ancillary"),
                    (4, "External Images"),
                ]
            ),
        ),
    ]
