# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0024_auto_20170716_1252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageCondition',
        ),
    ]
