# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 14:51
from __future__ import unicode_literals

import diamm.helpers.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0025_delete_pagecondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='logo',
            field=models.FileField(blank=True, null=True, storage=diamm.helpers.storage.OverwriteStorage(), upload_to='archives/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='incipit',
            field=models.FileField(blank=True, null=True, storage=diamm.helpers.storage.OverwriteStorage(), upload_to='rism/incipits/'),
        ),
    ]
