# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-22 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0026_auto_20170716_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliographypublication',
            name='type',
            field=models.IntegerField(choices=[(1, 'Volume Number'), (2, 'Title of Parent Entry (i.e., Book title, Journal title)'), (3, 'Title and Location of Publisher'), (4, 'Pages'), (5, 'University and Department (for Dissertations)'), (6, 'Degree (for Dissertations)'), (8, 'Series Title (NB: Use Parent Title for journal names)'), (9, 'URL'), (10, 'URL Accessed Date'), (11, 'Translator Statement'), (12, 'Festschrift Dedicatee'), (13, 'Place of Publication'), (14, 'Number of Volumes in Series'), (15, 'ISBN/ISSN/ISMN')]),
        ),
    ]
