# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-22 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0021_auto_20170708_2252'),
        ('diamm_data', '0027_auto_20170722_1931'),
    ]

    operations = [
    ]
