# Generated by Django 5.2.7 on 2025-10-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0027_alter_genre_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_title",
            field=models.CharField(
                blank=True,
                help_text='A title for this item record, ONLY if it is NOT linked to a composition. This is for\n                         supplying a name to otherwise untitled things (e.g., "blank page") or\n                         for non-musical titles ("A Poem").\n\n                         Use the Source Incipit field to record variant titles for compositions.\n                 ',
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="source_incipit",
            field=models.TextField(
                blank=True,
                help_text="The incipit or title of the piece given in the source",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="end_date",
            field=models.IntegerField(
                blank=True,
                help_text="Enter the end year as a four digit integer. If the\n                     precise year is not known, enter it rounding UP to the\n                     closest known decade, and then century. Examples: 1456, 1460, 1500.\n                     ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="start_date",
            field=models.IntegerField(
                blank=True,
                help_text="Enter the start year as a four digit integer. If\n                    the precise year is not known, enter it rounding DOWN to the closest\n                    known decade, and then century. Examples: 1456, 1450, 1400.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="A brief description of the source, e.g, 'chant book with added polyphony'",
                max_length=255,
                null=True,
            ),
        ),
    ]
