# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0028_merge_20170722_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Page'), (2, 'Modern Endpapers'), (3, 'Contemporary Endpapers'), (4, 'Flyleaf'), (5, 'Opening'), (6, 'Bindings'), (7, 'Fragment(s)'), (8, 'Scroll'), (9, 'Additional'), (11, 'Pastedown'), (12, 'Offset'), (10, 'Secondary')], default=1, null=True),
        ),
    ]
