# Generated by Django 5.2.7 on 2025-10-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0028_alter_item_item_title_alter_item_source_incipit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="has_medieval_foliation",
            field=models.BooleanField(
                default=False,
                help_text="Is the foliation in use from the medieval period?",
            ),
        ),
    ]
