# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0029_auto_20170831_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='personrole',
            name='earliest_year_uncertain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personrole',
            name='latest_year_uncertain',
            field=models.BooleanField(default=False),
        ),
    ]
