# Generated by Django 5.2.7 on 2025-10-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0029_source_has_medieval_foliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="original_format",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Rotulus"), (2, "Codex"), (3, "Libellus"), (4, "Unknown")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="original_format_uncertain",
            field=models.BooleanField(default=False),
        ),
    ]
