# Generated by Django 5.2.7 on 2025-10-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0030_source_original_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="current_state",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Fragment"), (2, "Complete"), (3, "Lost")],
                null=True,
            ),
        ),
    ]
