# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0030_auto_20170929_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personrole',
            old_name='earliest_year_uncertain',
            new_name='earliest_year_approximate',
        ),
        migrations.RenameField(
            model_name='personrole',
            old_name='latest_year_uncertain',
            new_name='latest_year_approximate',
        ),
    ]
