# Generated by Django 5.2.7 on 2025-10-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0031_source_current_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="current_host",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name=[
                    (1, "Removed from host manuscript"),
                    (2, "Still within host manuscript"),
                    (3, "Within fragment collection"),
                ],
            ),
        ),
    ]
