# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 02:42
from __future__ import unicode_literals

import diamm.models.data.source_note
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0032_auto_20171116_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliographypublication',
            name='type',
            field=models.IntegerField(choices=[(1, 'Volume Number'), (2, 'Title of Parent Entry (i.e., Book title, Journal title)'), (3, 'Publisher'), (4, 'Pages'), (5, 'University and Department (for Dissertations)'), (6, 'Degree (for Dissertations)'), (8, 'Series Title (NB: Use Parent Title for journal names)'), (9, 'URL'), (10, 'URL Accessed Date'), (11, 'Translator Statement'), (12, 'Festschrift Dedicatee'), (13, 'Place of Publication'), (14, 'Number of Volumes in Series'), (15, 'ISBN/ISSN/ISMN'), (99, 'General Note')]),
        ),
        migrations.AlterField(
            model_name='sourcenote',
            name='author',
            field=models.CharField(blank=True, default=diamm.models.data.source_note.get_default_author, max_length=255, null=True),
        ),
    ]
