# Generated by Django 5.2.7 on 2025-10-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0032_source_current_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="original_main_contents",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Liturgical book"),
                    (2, "Miscellany"),
                    (3, "Accounts"),
                    (4, "Polyphony"),
                    (5, "Songbook"),
                    (6, "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="current_host",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Removed from host manuscript"),
                    (2, "Still within host manuscript"),
                    (3, "Within fragment collection"),
                ],
                null=True,
            ),
        ),
    ]
