# Generated by Django 5.2.7 on 2025-10-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0033_source_original_main_contents_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="original_main_contents",
        ),
        migrations.AddField(
            model_name="source",
            name="host_main_contents",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Liturgical book"),
                    (2, "Miscellany"),
                    (3, "Accounts"),
                    (4, "Polyphony"),
                    (5, "Songbook"),
                    (6, "Other"),
                ],
                help_text="Indicate the main contents of the host manuscript, particularly if only a few pages of the whole volume contain music.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="current_host",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Removed from host manuscript"),
                    (2, "Still within host manuscript"),
                    (3, "Within fragment collection"),
                ],
                help_text="The present host of the manuscript",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="current_state",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Fragment"), (2, "Complete"), (3, "Lost")],
                help_text="The current state of the manuscript",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="original_format_uncertain",
            field=models.BooleanField(
                default=False,
                help_text="Used in conjunction with the original format field; indicates that the format declared there is not certain.",
            ),
        ),
    ]
