# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0033_auto_20171119_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Alternate Title'), (2, 'Pars')])),
                ('note', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='diamm_data.Composition')),
            ],
        ),
    ]
