# Generated by Django 5.2.7 on 2025-10-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0034_remove_source_original_main_contents_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSubtype",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="None", max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="subtypes",
            field=models.ManyToManyField(
                blank=True, to="diamm_data.organizationsubtype"
            ),
        ),
    ]
