# Generated by Django 5.2.7 on 2025-10-16 14:36

from django.db import migrations

def add_fixed_subtypes(apps, schema_editor):
    OrganizationSubtype = apps.get_model("diamm_data", "OrganizationSubtype")
    OrganizationSubtype.objects.bulk_create([
        OrganizationSubtype(name="Benedictine Cathedral"),
        OrganizationSubtype(name="Benedictine Abbey/Nunnery"),
        OrganizationSubtype(name="Cistercian Abbey/Nunnery"),
        OrganizationSubtype(name="Augustinian Abbey/Nunnery"),
        OrganizationSubtype(name="Gilbertine Priory"),
        OrganizationSubtype(name="Secular Cathedral"),
        OrganizationSubtype(name="Collegiate Church"),
        OrganizationSubtype(name="Parish Church"),
        OrganizationSubtype(name="Royal Chapel"),
        OrganizationSubtype(name="Noble Household")
    ])


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0035_organizationsubtype_organization_subtypes"),
    ]

    operations = [ migrations.RunPython(add_fixed_subtypes) ]
