# Generated by Django 5.2.7 on 2025-10-20 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0036_auto_20251016_1436"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="notation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="diamm_data.notation",
            ),
        ),
    ]
