# Generated by Django 5.2.7 on 2025-10-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0037_item_notation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compositionbibliography",
            options={"verbose_name_plural": "Composition Bibliographies"},
        ),
        migrations.AlterModelOptions(
            name="text",
            options={"ordering": ("incipit", "id")},
        ),
        migrations.AlterModelOptions(
            name="voice",
            options={"ordering": ("sort_order", "item__composition__title")},
        ),
        migrations.AddField(
            model_name="item",
            name="bibliography_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bibliographypublication",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Volume (and Issue) Number"),
                    (2, "Title of Parent Entry (i.e., Book title, Journal title)"),
                    (3, "Publisher"),
                    (4, "Pages"),
                    (5, "University and Department (for Dissertations)"),
                    (6, "Degree (for Dissertations)"),
                    (8, "Series Title (NB: Use Parent Title for journal names)"),
                    (9, "URL"),
                    (10, "URL Accessed Date"),
                    (11, "Translator Statement"),
                    (12, "Festschrift Dedicatee"),
                    (13, "Place of Publication"),
                    (14, "Number of Volumes in Series"),
                    (15, "ISBN/ISSN/ISMN"),
                    (16, "Conference name"),
                    (17, "Conference location"),
                    (18, "Conference date"),
                    (99, "General Note"),
                ]
            ),
        ),
    ]
