# Generated by Django 5.2.7 on 2025-10-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0039_rename_convert_position_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="numbering_system",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Mixed Foliation and Pagination"),
                    (2, "Foliation"),
                    (3, "Pagination"),
                    (4, "None / Unknown"),
                    (5, "Signatures"),
                    (6, "Mixed Foliation and Signatures"),
                    (7, "Mixed Pagination and Signatures"),
                ],
                null=True,
            ),
        ),
    ]
