# Generated by Django 5.2.7 on 2025-10-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0040_alter_source_numbering_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="completeness",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Text only"),
                    (2, "Music only"),
                    (3, "Missing; mentioned in index"),
                    (4, "Catchword only"),
                ],
                help_text='Indicates the completeness of the written composition in the source. Used when the\ncomposition is nominally "whole" within the source, but presents an incomplete view of the composition.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="fragment",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the item represents a fragment of the composition. Only used when\nthe composition is missing due to physical damage to the MS; do not use for partially-written compositions, compositions\nmissing voices, or compositions that contain only text or only music.",
                null=True,
            ),
        ),
    ]
