# Generated by Django 5.2.7 on 2025-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0041_item_completeness_item_fragment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="fragment",
            field=models.BooleanField(
                default=False,
                help_text="Whether the item represents a fragment of the composition. Only used when\nthe composition is missing due to physical damage to the MS; do not use for partially-written compositions, compositions\nmissing voices, or compositions that contain only text or only music.",
            ),
        ),
    ]
