# Generated by Django 5.2.7 on 2025-11-03 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0042_alter_item_fragment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CycleComposer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uncertain", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "composer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="diamm_data.person",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composers",
                        to="diamm_data.cycle",
                    ),
                ),
            ],
            options={
                "ordering": ("cycle__title",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cycle", "composer"),
                        name="uniq_cyclecomposer_cycle_composer",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO diamm_data_cyclecomposer (cycle_id, composer_id, uncertain, notes)
                SELECT c.id, c.composer_id, FALSE, NULL
                FROM diamm_data_cycle AS c
                WHERE c.composer_id IS NOT NULL
                ON CONFLICT (cycle_id, composer_id) DO NOTHING;
                """,
            reverse_sql="""
                        UPDATE diamm_data_cycle AS c
                        SET composer_id = cc.composer_id
                        FROM (
                            SELECT DISTINCT ON (cycle_id) cycle_id, composer_id
                            FROM diamm_data_cyclecomposer
                            ORDER BY cycle_id, id
                        ) AS cc
                        WHERE c.id = cc.cycle_id;
                        """,
        ),
    ]
