# Generated by Django 5.2.7 on 2025-11-03 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0043_cyclecomposer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cycle",
            name="composer",
        ),
        migrations.AddField(
            model_name="cycle",
            name="composers",
            field=models.ManyToManyField(
                related_name="composed_cycles",
                through="diamm_data.CycleComposer",
                to="diamm_data.person",
            ),
        ),
        migrations.AlterField(
            model_name="cyclecomposer",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="diamm_data.cycle"
            ),
        ),
    ]
