# Generated by Django 5.2.7 on 2025-11-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0044_remove_cycle_composer_cycle_composers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="diamm_has_images",
            field=models.BooleanField(
                default=False,
                help_text="DIAMM has images but does not have permission to put them online.",
            ),
        ),
        migrations.AlterField(
            model_name="itemnote",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "General Note"),
                    (2, "Copying Style"),
                    (3, "Concordances"),
                    (4, "Layout"),
                    (5, "Position on Page"),
                    (6, "Non-music contents description"),
                    (7, "Indexing or Ordering"),
                    (8, "Physical description (Condition, Legibility, etc.)"),
                    (99, "Internal Note"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="page_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Page"),
                    (2, "Modern Endpapers"),
                    (3, "Contemporary Endpapers"),
                    (4, "Flyleaf"),
                    (5, "Opening"),
                    (6, "Bindings"),
                    (7, "Fragment(s)"),
                    (8, "Scroll"),
                    (9, "Additional"),
                    (10, "Pastedown"),
                    (11, "Offset"),
                    (12, "Secondary"),
                ],
                default=1,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("public_images", True), ("diamm_has_images", True), _negated=True
                ),
                name="mutually_exclusive_images",
            ),
        ),
    ]
