# Generated by Django 5.2.7 on 2025-11-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0045_source_diamm_has_images_alter_itemnote_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="diamm_has_images",
            field=models.BooleanField(
                default=False,
                help_text="DIAMM has images but does not have permission to put them online.",
                verbose_name="DIAMM has images",
            ),
        ),
    ]
