# Generated by Django 6.0.7 on 2026-07-18 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0046_alter_source_diamm_has_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceToSourceRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SourceToSourceRelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_label', models.CharField(max_length=512)),
                ('inverse_label', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ('forward_label',),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='copied_from',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copied_items', to='diamm_data.item'),
        ),
        migrations.AddField(
            model_name='page',
            name='copied_from',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copied_pages', to='diamm_data.page'),
        ),
        migrations.AddField(
            model_name='source',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='This source is a virtual reconstruction assembled from other sources.'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('copied_from__isnull', False)), fields=('source', 'copied_from'), name='unique_copied_item_per_source'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(condition=models.Q(('copied_from__isnull', False)), fields=('source', 'copied_from'), name='unique_copied_page_per_source'),
        ),
        migrations.AddField(
            model_name='sourcetosourcerelationship',
            name='from_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_source_relationships', to='diamm_data.source'),
        ),
        migrations.AddField(
            model_name='sourcetosourcerelationship',
            name='to_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_source_relationships', to='diamm_data.source'),
        ),
        migrations.AddField(
            model_name='source',
            name='related_sources',
            field=models.ManyToManyField(blank=True, related_name='related_to_sources', through='diamm_data.SourceToSourceRelationship', through_fields=('from_source', 'to_source'), to='diamm_data.source'),
        ),
        migrations.AlterConstraint(
            model_name='source',
            name='mutually_exclusive_images',
            constraint=models.CheckConstraint(condition=models.Q(('public_images', True), ('diamm_has_images', True), _negated=True), name='mutually_exclusive_images', violation_error_message='You cannot select both DIAMM has images but no permission, and public images.'),
        ),
        migrations.AddField(
            model_name='sourcetosourcerelationship',
            name='relationship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships', to='diamm_data.sourcetosourcerelationshiptype'),
        ),
        migrations.AddConstraint(
            model_name='sourcetosourcerelationship',
            constraint=models.CheckConstraint(condition=models.Q(('from_source', models.F('to_source')), _negated=True), name='source_relation_not_self'),
        ),
        migrations.AddConstraint(
            model_name='sourcetosourcerelationship',
            constraint=models.UniqueConstraint(fields=('from_source', 'to_source', 'relationship_type'), name='unique_directed_source_relation'),
        ),
    ]
