# Generated by Django 6.0.7 on 2026-07-18 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0047_virtual_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Edition'), (2, 'Score')])),
                ('link_text', models.CharField(blank=True, help_text='A description of the linked edition or score.', max_length=1024, null=True)),
                ('link', models.URLField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='diamm_data.composition')),
            ],
            options={
                'verbose_name': 'Composition URL',
                'verbose_name_plural': 'Composition URLs',
                'ordering': ('type', 'pk'),
            },
        ),
    ]
