# Generated by Django 6.0.7 on 2026-08-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("diamm_data", "0048_composition_external_links")]

    operations = [
        migrations.RemoveField(model_name="source", name="host_main_contents"),
        migrations.AddField(
            model_name="source",
            name="original_main_contents",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Liturgical book"),
                    (2, "Miscellany"),
                    (3, "Accounts"),
                    (4, "Polyphony"),
                    (5, "Songbook"),
                    (6, "Other"),
                ],
                help_text="Please use this field to capture what the main contents of the source are: if the source is music fragment bound with another volume, please use this field to describe the contents of fragment, not the host volume.",
                null=True,
            ),
        ),
    ]
