[tool.poetry]
name = "diamm"
version = "1.11.1"
description = ""
authors = ["Andrew Hankinson <andrew.hankinson@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "~=3.0"
djangorestframework = "^3.11.0"
django-extensions = "^2.2.9"
werkzeug = "^1.0.0"
django-registration = "3.2"
django-dynamic-raw-id = "^2.6"
jinja2 = "^3.0"
django-jinja = "^2.6.0"
pysolr = "^3.8.1"
django-pagedown = "^2.0.3"
django-reversion = "^3.0.7"
psycopg2-binary = "^2.8.4"
ujson = "^2.0.3"
serpy = "^0.3.1"
markdown2 = "^2.3.8"
gunicorn = "^20.0.4"
blessings = "^1.7"
wagtail = "2.15"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
ipython = "7.34"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
