[tool.poetry]
name = "diamm"
version = "1.11.1"
description = ""
authors = ["Andrew Hankinson <andrew.hankinson@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
django = "~=5.0"
wagtail = "^6.0"
djangorestframework = "^3.11.0"
django-extensions = "^3.0"
django-registration = "^3.1"
jinja2 = "^3.0"
django-jinja = "^2.6.0"
pysolr = { git = "https://github.com/django-haystack/pysolr/", rev="master"}
django-pagedown = "^2.0.3"
django-reversion = "^5.0"
ujson = "^5.0"
serpy = "^0.3.1"
markdown2 = "^2.3.8"
gunicorn = "^22.0.0"
blessings = "^1.7"
ipython = "^8.24.0"
tablib = "^3.5.0"
requests = "2.31.0"
traitlets = "^5.14.3"
Pillow = "^9.0"
markupsafe = "^2.0.1"
psycopg = "^3.1.9"
aiohttp = {extras = ["speedups"], version = "^3.8.5"}
werkzeug = "^3.0.3"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^4.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
