from diamm.admin.diamm_user import UserAdmin
from diamm.admin.site.problem_report import ProblemReportAdmin
from diamm.admin.site.commentary import CommentaryAdmin

from diamm.admin.data.source import SourceAdmin
from diamm.admin.data.source_catalogue_entry import SourceCatalogueEntryAdmin
from diamm.admin.data.page import PageAdmin
from diamm.admin.data.page_note import PageNoteAdmin
from diamm.admin.data.source_relationship import SourceRelationshipAdmin
from diamm.admin.data.source_provenance import SourceProvenanceAdmin
from diamm.admin.data.source_note import SourceNoteAdmin
from diamm.admin.data.geographic_area import GeographicAreaAdmin
from diamm.admin.data.archive import ArchiveAdmin
from diamm.admin.data.archive_note import ArchiveNoteAdmin
from diamm.admin.data.genre import GenreAdmin
from diamm.admin.data.person import PersonAdmin
from diamm.admin.data.organization import OrganizationAdmin
from diamm.admin.data.organization_type import OrganizationTypeAdmin
from diamm.admin.data.bibliography import BibliographyAdmin
from diamm.admin.data.bibliography_author import BibliographyAuthorAdmin
from diamm.admin.data.composition import CompositionAdmin
from diamm.admin.data.image import ImageAdmin
from diamm.admin.data.item import ItemAdmin
from diamm.admin.data.item_note import ItemNoteAdmin
from diamm.admin.data.source_copyist import SourceCopyistAdmin
from diamm.admin.diamm_user import UserAdmin
from diamm.admin.data.set import SetAdmin
from diamm.admin.data.text import TextAdmin
from diamm.admin.data.voice import VoiceAdmin
from diamm.admin.data.voice_type import VoiceTypeAdmin
from diamm.admin.data.cycle import CycleAdmin
from diamm.admin.data.cycle_type import CycleTypeAdmin
from diamm.admin.data.clef import ClefAdmin
from diamm.admin.data.image_type import ImageTypeAdmin
from diamm.admin.data.language import LanguageAdmin
from diamm.admin.data.mensuration import MensurationAdmin
from diamm.admin.data.notation import NotationAdmin

