# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_site', '0002_commentary_contentpage_homepage_newsindexpage_newspage_problemreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
