# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
        ('diamm_site', '0003_auto_20161216_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
