# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 17:04
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_site', '0005_publicationpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='pricing',
            field=wagtail.wagtailcore.fields.StreamField((('price', wagtail.wagtailcore.blocks.StructBlock((('description', wagtail.wagtailcore.blocks.CharBlock()), ('price', wagtail.wagtailcore.blocks.IntegerBlock())))),)),
        ),
    ]
