# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_site', '0007_publicationpage_purchase_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='tmpl',
            field=models.FilePathField(blank=True, null=True, verbose_name='/Users/ahankins/Documents/code/git/diamm/templates/website/cms/content_path'),
        ),
    ]
