# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_site', '0008_contentpage_tmpl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='tmpl',
            field=models.FilePathField(blank=True, match='.*\\.jinja2', max_length=255, null=True, path='/Users/ahankins/Documents/code/git/diamm/diamm/templates/website/cms/content_page', verbose_name='Template'),
        ),
    ]
