# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 16:46
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_site', '0009_auto_20161218_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='pricing',
            field=wagtail.core.fields.StreamField((('price', wagtail.core.blocks.StructBlock((('description', wagtail.core.blocks.CharBlock()), ('price', wagtail.core.blocks.DecimalBlock())), template='website/blocks/pricing_field.jinja2')),)),
        ),
    ]
