# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_site', '0012_auto_20161220_1719'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='dissertationpage',
    #         name='author',
    #         field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='diamm_data.BibliographyAuthor'),
    #     ),
    # ]
