# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_site', '0013_auto_20161220_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertationpage',
            name='author',
        ),
    ]
