# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_site', '0015_auto_20170119_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemreport',
            name='credit',
            field=models.CharField(blank=True, help_text='Use this field to acknowledge credit without tying the contribution to a specific user account. A record\n    should either have a contributor or a credit acknowledgement.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='contributor',
            field=models.ForeignKey(blank=True, help_text="Use this field to attach a contribution to a DIAMM user account. By doing this (instead of\n    simply using the 'credit' field) DIAMM users will be able to see a record of their own contributions on their account\n    profile page.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
