# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_data', '0010_auto_20170123_1608'),
        ('diamm_site', '0016_auto_20170119_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertationpage',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='diamm_data.BibliographyAuthor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='summary',
            field=models.TextField(blank=True, help_text="A summary of the change that was contributed by the user. Used to automatically build a contributor's entry for the record", null=True),
        ),
    ]
