# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_site', '0018_homepage_publications_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='show_on_front',
            field=models.BooleanField(default=False),
        ),
    ]
