# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_site', '0022_auto_20170326_0721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemreport',
            options={'ordering': ('accepted',)},
        ),
    ]
