# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_site', '0022_auto_20170326_0721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemreport',
            options={'ordering': ('accepted',)},
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='tmpl',
            field=models.FilePathField(blank=True, match='.*\\.jinja2', max_length=255, null=True, path='/srv/www.diamm.ac.uk/webapps/diamm/diamm/templates/website/cms/content_page', verbose_name='Template'),
        ),
    ]
