# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_site', '0023_auto_20170527_1613'),
        ('diamm_site', '0023_auto_20170425_1714'),
    ]

    operations = [
    ]
