# Generated by Django 2.0.4 on 2018-04-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_site', '0027_auto_20170803_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'diamm_data'), ('model', 'source')), models.Q(('app_label', 'diamm_data'), ('model', 'page')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'diamm_data'), ('model', 'person')), models.Q(('app_label', 'diamm_data'), ('model', 'organization')), models.Q(('app_label', 'diamm_data'), ('model', 'source')), models.Q(('app_label', 'diamm_data'), ('model', 'composition')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
