# Generated by Django 3.2.16 on 2022-10-14 12:58

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('diamm_site', '0028_auto_20180423_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='carousel',
            field=wagtail.fields.StreamField([('carousel', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.TextBlock())], template='website/blocks/carousel.jinja2'))], use_json_field=False),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='pricing',
            field=wagtail.fields.StreamField([('price', wagtail.blocks.StructBlock([('description', wagtail.blocks.CharBlock()), ('price', wagtail.blocks.DecimalBlock()), ('purchase_link', wagtail.blocks.URLBlock())], template='website/blocks/pricing_field.jinja2'))], use_json_field=False),
        ),
    ]
