# Generated by Django 5.1.5 on 2025-02-19 12:48

from django.db import migrations


# Clean up the old authtoken table now that we have a new DIAMM Token table.
class Migration(migrations.Migration):
    dependencies = [
        ("diamm_site", "0031_diammtoken"),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "authtoken_token"',
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
