# Generated by Django 5.2.7 on 2025-11-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_site", "0032_auto_20250219_1248"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="tmpl",
            field=models.FilePathField(
                blank=True,
                match=".*\\.jinja2",
                max_length=255,
                null=True,
                path="/srv/www.diamm.ac.uk/webapps/diamm/diamm/templates/website/cms/content_page",
                verbose_name="Template",
            ),
        ),
    ]
