# Generated by Django 5.2.7 on 2025-11-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_site", "0033_alter_contentpage_tmpl"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dissertationpage",
            options={"ordering": ("author__last_name", "year")},
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="tmpl",
            field=models.FilePathField(
                blank=True,
                match=".*\\.jinja2",
                max_length=255,
                null=True,
                path="/Users/ahankins/Documents/code/git/diamm/diamm/templates/website/cms/content_page",
                verbose_name="Template",
            ),
        ),
    ]
