# Generated by Django 5.2.7 on 2025-11-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0044_remove_cycle_composer_cycle_composers_and_more"),
        ("diamm_site", "0034_alter_dissertationpage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSources",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project", models.CharField(max_length=128)),
                (
                    "sources",
                    models.ManyToManyField(
                        related_name="projects", to="diamm_data.source"
                    ),
                ),
            ],
        ),
    ]
