# Generated by Django 5.2.7 on 2025-11-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("diamm_site", "0035_projectsources"),
        ("diamm_site", "0036_projectsources_slug_alter_projectsources_sources"),
        ("diamm_site", "0037_alter_projectsources_options_and_more"),
    ]

    dependencies = [
        ("diamm_data", "0044_remove_cycle_composer_cycle_composers_and_more"),
        ("diamm_site", "0034_alter_dissertationpage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSources",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project", models.CharField(max_length=128)),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="diamm_data.source"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A value for this project that is used in a filter. Auto-filled from the title, but it can be modified here. No spaces allowed, only lower-case letters and hyphens."
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project sources",
            },
        ),
    ]
