# Generated by Django 5.2.7 on 2025-11-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0044_remove_cycle_composer_cycle_composers_and_more"),
        ("diamm_site", "0035_projectsources"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsources",
            name="slug",
            field=models.SlugField(default="brokensong"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projectsources",
            name="sources",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="projects", to="diamm_data.source"
            ),
        ),
    ]
