# Generated by Django 5.2.7 on 2025-11-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamm_data", "0044_remove_cycle_composer_cycle_composers_and_more"),
        ("diamm_site", "0036_projectsources_slug_alter_projectsources_sources"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectsources",
            options={"verbose_name_plural": "Project sources"},
        ),
        migrations.AlterField(
            model_name="projectsources",
            name="slug",
            field=models.SlugField(
                help_text="A value for this project that is used in a filter. Auto-filled from the title, but it can be modified here. No spaces allowed, only lower-case letters and hyphens."
            ),
        ),
        migrations.AlterField(
            model_name="projectsources",
            name="sources",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="diamm_data.source"
            ),
        ),
    ]
